FROM ghcr.io/anomalyco/opencode

USER root
WORKDIR /root

COPY tools/starship.toml ./.config/starship.toml
COPY tools/bashrc ./.bashrc
COPY tools/shrc ./.shrc

RUN set -eux; \
    apk add --no-cache git vim diffutils grep gawk aws-cli \
        mariadb-client curl wget jq \
        nodejs npm composer bash openssl starship docker-cli;ß

SHELL ["/bin/bash", "-euo", "pipefail", "-c"]
