name: opencode
services:
  opencode:
    build:
      context: .
      dockerfile: Dockerfile.oc
    container_name: opencode
    command: ["web", "--port", "4012", "--hostname", "0.0.0.0"]
    ports:
      - "9000:9000"
      - "4012:4012"
    environment:
      OPENCODE_SERVER_USERNAME: ${OPENCODE_SERVER_USERNAME:-admin}
      OPENCODE_SERVER_PASSWORD: ${OPENCODE_SERVER_PASSWORD:-abc123}
      WORKDIR: /workspace
    volumes:
      - ./workspace:/workspace
      - ./opencode:/root/.config/opencode
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /workspace
